markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Domain of C.Y.J
subTitle: Welcome to C.Y.J's blog.
description: This is my personal blog, which is built by Jekyll and the template is powered by zhanxin.info.
url: http://chengyuanjian.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
  - text: Archives
    url: /archives.html
  - text: Resume
    url: /resume.html
  - text: Source
    url: https://github.com/ChengYuanjian/chengyuanjian.github.io

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
#headimg:
  #- item: /themes/violet/images/hdbg01.jpg
  #- item: /themes/violet/images/hdbg02.jpg
  #- item: /themes/violet/images/hdbg03.jpg
  #- item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://plus.google.com
  - class: fa-facebook
    url: http://www.facebook.com/_Aegwynn
  - class: fa-github
    url: http://github.com/ChengYuanjian
  - class: fa-weibo
    url: http://weibo.com/_Aegwynn
  - class: fa-renren
    url: 
  - class: fa-pinterest
    url: 
  - class: fa-twitter
    url: http://www.twitter.com/_Aegwynn
  - class: fa-rss
    url: http://github.com/ChengYuanjian

#作者信息
author:
  link: http://github.com/ChengYuanjian
  img: 

#评论信息
disqus:
  config: true
  id: guest

duoshuo:
  config: false
  id: guest
